// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_09dIYoCjLHG_6cT0Sb-2xhSEUM5ppn4',
    appId: '1:1045893033865:web:73b52daa1a003dce1dbb58',
    messagingSenderId: '1045893033865',
    projectId: 'chatgpt-app-b3301',
    authDomain: 'chatgpt-app-b3301.firebaseapp.com',
    storageBucket: 'chatgpt-app-b3301.firebasestorage.app',
    measurementId: 'G-2G82P007NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-GJsQWf7kVPKSTcUxKb_1E5oHKYA-_4',
    appId: '1:1045893033865:android:9761892c12c41d7b1dbb58',
    messagingSenderId: '1045893033865',
    projectId: 'chatgpt-app-b3301',
    storageBucket: 'chatgpt-app-b3301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoND4ZMDfO-yUgYwgTmUHaQR_tPrr7I-s',
    appId: '1:1045893033865:ios:76fcc894bf2057591dbb58',
    messagingSenderId: '1045893033865',
    projectId: 'chatgpt-app-b3301',
    storageBucket: 'chatgpt-app-b3301.firebasestorage.app',
    iosBundleId: 'com.example.chatGptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoND4ZMDfO-yUgYwgTmUHaQR_tPrr7I-s',
    appId: '1:1045893033865:ios:76fcc894bf2057591dbb58',
    messagingSenderId: '1045893033865',
    projectId: 'chatgpt-app-b3301',
    storageBucket: 'chatgpt-app-b3301.firebasestorage.app',
    iosBundleId: 'com.example.chatGptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_09dIYoCjLHG_6cT0Sb-2xhSEUM5ppn4',
    appId: '1:1045893033865:web:8ee01d2b622b9a961dbb58',
    messagingSenderId: '1045893033865',
    projectId: 'chatgpt-app-b3301',
    authDomain: 'chatgpt-app-b3301.firebaseapp.com',
    storageBucket: 'chatgpt-app-b3301.firebasestorage.app',
    measurementId: 'G-G75XX0YWXY',
  );
}
